# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_service import ml_service_pb2 as grpc__service_dot_ml__service__pb2

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in grpc_service/ml_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class MLServiceStub(object):
    """Сервис для ML операций"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Train = channel.unary_unary(
            "/ml_service.MLService/Train",
            request_serializer=grpc__service_dot_ml__service__pb2.TrainRequest.SerializeToString,
            response_deserializer=grpc__service_dot_ml__service__pb2.TrainResponse.FromString,
            _registered_method=True,
        )
        self.ListAvailableModels = channel.unary_unary(
            "/ml_service.MLService/ListAvailableModels",
            request_serializer=grpc__service_dot_ml__service__pb2.Empty.SerializeToString,
            response_deserializer=grpc__service_dot_ml__service__pb2.AvailableModelsResponse.FromString,
            _registered_method=True,
        )
        self.Predict = channel.unary_unary(
            "/ml_service.MLService/Predict",
            request_serializer=grpc__service_dot_ml__service__pb2.PredictRequest.SerializeToString,
            response_deserializer=grpc__service_dot_ml__service__pb2.PredictResponse.FromString,
            _registered_method=True,
        )
        self.Retrain = channel.unary_unary(
            "/ml_service.MLService/Retrain",
            request_serializer=grpc__service_dot_ml__service__pb2.RetrainRequest.SerializeToString,
            response_deserializer=grpc__service_dot_ml__service__pb2.RetrainResponse.FromString,
            _registered_method=True,
        )
        self.DeleteModel = channel.unary_unary(
            "/ml_service.MLService/DeleteModel",
            request_serializer=grpc__service_dot_ml__service__pb2.DeleteRequest.SerializeToString,
            response_deserializer=grpc__service_dot_ml__service__pb2.DeleteResponse.FromString,
            _registered_method=True,
        )
        self.ListTrainedModels = channel.unary_unary(
            "/ml_service.MLService/ListTrainedModels",
            request_serializer=grpc__service_dot_ml__service__pb2.Empty.SerializeToString,
            response_deserializer=grpc__service_dot_ml__service__pb2.TrainedModelsResponse.FromString,
            _registered_method=True,
        )
        self.GetModelInfo = channel.unary_unary(
            "/ml_service.MLService/GetModelInfo",
            request_serializer=grpc__service_dot_ml__service__pb2.ModelInfoRequest.SerializeToString,
            response_deserializer=grpc__service_dot_ml__service__pb2.ModelInfoResponse.FromString,
            _registered_method=True,
        )
        self.HealthCheck = channel.unary_unary(
            "/ml_service.MLService/HealthCheck",
            request_serializer=grpc__service_dot_ml__service__pb2.Empty.SerializeToString,
            response_deserializer=grpc__service_dot_ml__service__pb2.HealthResponse.FromString,
            _registered_method=True,
        )


class MLServiceServicer(object):
    """Сервис для ML операций"""

    def Train(self, request, context):
        """Обучить новую модель"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListAvailableModels(self, request, context):
        """Получить список доступных классов моделей"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Predict(self, request, context):
        """Получить предсказания"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Retrain(self, request, context):
        """Переобучить существующую модель"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteModel(self, request, context):
        """Удалить модель"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListTrainedModels(self, request, context):
        """Получить список обученных моделей"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetModelInfo(self, request, context):
        """Получить информацию о модели"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def HealthCheck(self, request, context):
        """Проверка статуса сервиса"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_MLServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Train": grpc.unary_unary_rpc_method_handler(
            servicer.Train,
            request_deserializer=grpc__service_dot_ml__service__pb2.TrainRequest.FromString,
            response_serializer=grpc__service_dot_ml__service__pb2.TrainResponse.SerializeToString,
        ),
        "ListAvailableModels": grpc.unary_unary_rpc_method_handler(
            servicer.ListAvailableModels,
            request_deserializer=grpc__service_dot_ml__service__pb2.Empty.FromString,
            response_serializer=grpc__service_dot_ml__service__pb2.AvailableModelsResponse.SerializeToString,
        ),
        "Predict": grpc.unary_unary_rpc_method_handler(
            servicer.Predict,
            request_deserializer=grpc__service_dot_ml__service__pb2.PredictRequest.FromString,
            response_serializer=grpc__service_dot_ml__service__pb2.PredictResponse.SerializeToString,
        ),
        "Retrain": grpc.unary_unary_rpc_method_handler(
            servicer.Retrain,
            request_deserializer=grpc__service_dot_ml__service__pb2.RetrainRequest.FromString,
            response_serializer=grpc__service_dot_ml__service__pb2.RetrainResponse.SerializeToString,
        ),
        "DeleteModel": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteModel,
            request_deserializer=grpc__service_dot_ml__service__pb2.DeleteRequest.FromString,
            response_serializer=grpc__service_dot_ml__service__pb2.DeleteResponse.SerializeToString,
        ),
        "ListTrainedModels": grpc.unary_unary_rpc_method_handler(
            servicer.ListTrainedModels,
            request_deserializer=grpc__service_dot_ml__service__pb2.Empty.FromString,
            response_serializer=grpc__service_dot_ml__service__pb2.TrainedModelsResponse.SerializeToString,
        ),
        "GetModelInfo": grpc.unary_unary_rpc_method_handler(
            servicer.GetModelInfo,
            request_deserializer=grpc__service_dot_ml__service__pb2.ModelInfoRequest.FromString,
            response_serializer=grpc__service_dot_ml__service__pb2.ModelInfoResponse.SerializeToString,
        ),
        "HealthCheck": grpc.unary_unary_rpc_method_handler(
            servicer.HealthCheck,
            request_deserializer=grpc__service_dot_ml__service__pb2.Empty.FromString,
            response_serializer=grpc__service_dot_ml__service__pb2.HealthResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "ml_service.MLService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("ml_service.MLService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class MLService(object):
    """Сервис для ML операций"""

    @staticmethod
    def Train(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ml_service.MLService/Train",
            grpc__service_dot_ml__service__pb2.TrainRequest.SerializeToString,
            grpc__service_dot_ml__service__pb2.TrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListAvailableModels(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ml_service.MLService/ListAvailableModels",
            grpc__service_dot_ml__service__pb2.Empty.SerializeToString,
            grpc__service_dot_ml__service__pb2.AvailableModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Predict(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ml_service.MLService/Predict",
            grpc__service_dot_ml__service__pb2.PredictRequest.SerializeToString,
            grpc__service_dot_ml__service__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Retrain(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ml_service.MLService/Retrain",
            grpc__service_dot_ml__service__pb2.RetrainRequest.SerializeToString,
            grpc__service_dot_ml__service__pb2.RetrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteModel(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ml_service.MLService/DeleteModel",
            grpc__service_dot_ml__service__pb2.DeleteRequest.SerializeToString,
            grpc__service_dot_ml__service__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListTrainedModels(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ml_service.MLService/ListTrainedModels",
            grpc__service_dot_ml__service__pb2.Empty.SerializeToString,
            grpc__service_dot_ml__service__pb2.TrainedModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetModelInfo(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ml_service.MLService/GetModelInfo",
            grpc__service_dot_ml__service__pb2.ModelInfoRequest.SerializeToString,
            grpc__service_dot_ml__service__pb2.ModelInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def HealthCheck(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/ml_service.MLService/HealthCheck",
            grpc__service_dot_ml__service__pb2.Empty.SerializeToString,
            grpc__service_dot_ml__service__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
